using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DfE.CheckPerformance.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class CheckingWindow_Changes : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "OrganisationType",
                table: "CheckingWindows");

            migrationBuilder.AlterColumn<string>(
                name: "Title",
                table: "CheckingWindows",
                type: "character varying(200)",
                maxLength: 200,
                nullable: false,
                oldClrType: typeof(string),
                oldType: "text");

            migrationBuilder.AlterColumn<DateTime>(
                name: "StartDate",
                table: "CheckingWindows",
                type: "timestamp without time zone",
                nullable: false,
                oldClrType: typeof(DateTime),
                oldType: "timestamp with time zone");

            migrationBuilder.AlterColumn<DateTime>(
                name: "EndDate",
                table: "CheckingWindows",
                type: "timestamp without time zone",
                nullable: false,
                oldClrType: typeof(DateTime),
                oldType: "timestamp with time zone");

            migrationBuilder.Sql(@"ALTER TABLE ""CheckingWindows"" ALTER COLUMN ""Id"" DROP IDENTITY;");
            migrationBuilder.Sql(@"ALTER TABLE ""CheckingWindows"" ALTER COLUMN ""Id"" TYPE uuid USING gen_random_uuid();");
            migrationBuilder.Sql(@"ALTER TABLE ""CheckingWindows"" ALTER COLUMN ""Id"" SET DEFAULT gen_random_uuid();");

            migrationBuilder.AddColumn<string>(
                name: "KeyStage",
                table: "CheckingWindows",
                type: "text",
                nullable: false,
                defaultValue: "");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "KeyStage",
                table: "CheckingWindows");

            migrationBuilder.AlterColumn<string>(
                name: "Title",
                table: "CheckingWindows",
                type: "text",
                nullable: false,
                oldClrType: typeof(string),
                oldType: "character varying(200)",
                oldMaxLength: 200);

            migrationBuilder.AlterColumn<DateTime>(
                name: "StartDate",
                table: "CheckingWindows",
                type: "timestamp with time zone",
                nullable: false,
                oldClrType: typeof(DateTime),
                oldType: "timestamp without time zone");

            migrationBuilder.AlterColumn<DateTime>(
                name: "EndDate",
                table: "CheckingWindows",
                type: "timestamp with time zone",
                nullable: false,
                oldClrType: typeof(DateTime),
                oldType: "timestamp without time zone");

            migrationBuilder.Sql(@"TRUNCATE TABLE ""CheckingWindows"";");
            migrationBuilder.Sql(@"ALTER TABLE ""CheckingWindows"" ALTER COLUMN ""Id"" DROP DEFAULT;");
            migrationBuilder.Sql(@"ALTER TABLE ""CheckingWindows"" ALTER COLUMN ""Id"" TYPE integer USING 0;");
            migrationBuilder.Sql(@"ALTER TABLE ""CheckingWindows"" ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;");

            migrationBuilder.AddColumn<int>(
                name: "OrganisationType",
                table: "CheckingWindows",
                type: "integer",
                nullable: false,
                defaultValue: 0);
        }
    }
}
