using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DfE.CheckPerformance.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class CheckingWindow_Steps : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<string>(
                name: "Title",
                table: "CheckingWindows",
                type: "character varying(200)",
                maxLength: 200,
                nullable: false,
                oldClrType: typeof(string),
                oldType: "text");

            migrationBuilder.AlterColumn<DateOnly>(
                name: "StartDate",
                table: "CheckingWindows",
                type: "date",
                nullable: false,
                oldClrType: typeof(DateTime),
                oldType: "timestamp with time zone");

            migrationBuilder.AlterColumn<DateOnly>(
                name: "EndDate",
                table: "CheckingWindows",
                type: "date",
                nullable: false,
                oldClrType: typeof(DateTime),
                oldType: "timestamp with time zone");

            migrationBuilder.Sql(@"ALTER TABLE ""CheckingWindows"" ALTER COLUMN ""Id"" DROP IDENTITY;");
            migrationBuilder.Sql(@"ALTER TABLE ""CheckingWindows"" ALTER COLUMN ""Id"" TYPE uuid USING gen_random_uuid();");

            migrationBuilder.CreateTable(
                name: "CheckingWindowSteps",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    CheckingWindowId = table.Column<Guid>(type: "uuid", nullable: false),
                    RequestType = table.Column<string>(type: "text", nullable: false),
                    StepType = table.Column<string>(type: "text", nullable: false),
                    Order = table.Column<int>(type: "integer", nullable: false),
                    IsRequired = table.Column<bool>(type: "boolean", nullable: false),
                    Title = table.Column<string>(type: "text", nullable: false),
                    Explanation = table.Column<string>(type: "text", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_CheckingWindowSteps", x => x.Id);
                    table.ForeignKey(
                        name: "FK_CheckingWindowSteps_CheckingWindows_CheckingWindowId",
                        column: x => x.CheckingWindowId,
                        principalTable: "CheckingWindows",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_CheckingWindowSteps_CheckingWindowId_RequestType_Order",
                table: "CheckingWindowSteps",
                columns: new[] { "CheckingWindowId", "RequestType", "Order" },
                unique: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "CheckingWindowSteps");

            migrationBuilder.AlterColumn<string>(
                name: "Title",
                table: "CheckingWindows",
                type: "text",
                nullable: false,
                oldClrType: typeof(string),
                oldType: "character varying(200)",
                oldMaxLength: 200);

            migrationBuilder.AlterColumn<DateTime>(
                name: "StartDate",
                table: "CheckingWindows",
                type: "timestamp with time zone",
                nullable: false,
                oldClrType: typeof(DateOnly),
                oldType: "date");

            migrationBuilder.AlterColumn<DateTime>(
                name: "EndDate",
                table: "CheckingWindows",
                type: "timestamp with time zone",
                nullable: false,
                oldClrType: typeof(DateOnly),
                oldType: "date");

            migrationBuilder.Sql(@"TRUNCATE TABLE ""CheckingWindows"" RESTART IDENTITY CASCADE;");
            migrationBuilder.Sql(@"ALTER TABLE ""CheckingWindows"" ALTER COLUMN ""Id"" TYPE integer USING 0;");
            migrationBuilder.Sql(@"ALTER TABLE ""CheckingWindows"" ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;");
        }
    }
}
